version: '3'

services:
  #Service Redis
  redis:
    container_name: redis
    hostname: redis
    image: redis

  #Interface Grafica do Usuario (GUI)
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=local:redis:6379
    ports:
      - "8081:8081"